package slot.play.cuan88;

import java.util.ArrayList;

public class GameData {
    public static String[][] data = new String[][]{
            {"Ultra Hold and Spin", "https://www.pragmaticplay.com/id/permainan/ultra-hold-and-spin-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/08/Ultra_Hold__Spin%E2%84%A2_EN_339x180.png"},
            {"Curse of the Werewolf", "https://www.pragmaticplay.com/id/permainan/curse-of-the-werewolf-megaways-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/08/Curse_of_the_Werewolf_Megaways%E2%84%A2_EN_339x180.png"},
            {"Jungle Gorilla", "https://www.pragmaticplay.com/id/permainan/jungle-gorilla-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/08/Jungle-Gorilla%E2%84%A2_EN_339x180_01.png"},
            {"Aztec Gems Deluxe", "https://www.pragmaticplay.com/id/permainan/aztec-gems-deluxe-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/07/Aztec-Gems%C3%94%C3%A4%C3%B3_EN_339x180_02.png"},
            {"The Dog House Megaways", "https://www.pragmaticplay.com/id/permainan/the-dog-house-megaways-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/07/DOHO_Megaways%E2%84%A2_EN_339x180.png"},
            {"The Tiger Warrior", "https://www.pragmaticplay.com/id/permainan/the-tiger-warrior-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/10/Tiger-Warrior%E2%84%A2_EN_339x180_02.png"},
            {"Street Racer", "https://www.pragmaticplay.com/id/permainan/street-racer-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/06/Street-Racer_%E2%84%A2_339x180_02.png"},
            {"Fu Fu Fu", "https://www.pragmaticplay.com/id/permainan/fu-fu-fu-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/10/FUFUFU%E2%84%A2_339x180.png"},
            {"Jewels of Fortune", "https://www.pragmaticplay.com/id/permainan/drago-jewels-of-fortune-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/06/Drago_JOF%E2%84%A2_339x180-1.png"},
            {"Bronco Spirit", "https://www.pragmaticplay.com/id/permainan/bronco-spirit-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/03/Bronco-Spirit%E2%84%A2_EN_339x180_01-2.png"},
            {"Pyramid King", "https://www.pragmaticplay.com/id/permainan/pyramid-king-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/06/Pyramid-King%E2%84%A2_339x180_02-1.png"},
            {"Ultra Burn", "https://www.pragmaticplay.com/id/permainan/ultra-burn-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/05/Ultra_Burn_EN_339x180-1.png"},
//            {"Belum ya", "https://www.pragmaticplay.com/id/permainan/ultra-burn-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/05/Ultra_Burn_EN_339x180-1.png"},
            {"Starz Megaways", "https://www.pragmaticplay.com/id/permainan/starz-megaways-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/05/Starz-Megaways%E2%84%A2_339x180-1.png"},
            {"Fruit Party", "https://www.pragmaticplay.com/id/permainan/fruit-party-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/05/Fruit-Party%E2%84%A2_339x180_01-1.png"},
            {"John Hunter and the Book of Tut", "https://www.pragmaticplay.com/id/permainan/john-hunter-and-the-book-of-tut-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/04/John-Hunter-Book-of-Tut%E2%84%A2_339x180-1-1.png"},
            {"Three Star Fortune", "https://www.pragmaticplay.com/id/permainan/three-star-fortune-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/06/Three-Star-Fortune_EN-_339x180-1.png"},
            {"Great Rhino Megaways", "https://www.pragmaticplay.com/id/permainan/great-rhino-megaways-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/04/Great-Rhino-Megaways%E2%84%A2_EN_339x180_02-2.png"},
            {"Dance Party", "https://www.pragmaticplay.com/id/permainan/dance-party-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/03/Dance-Party%E2%84%A2_EN_339x180_01-2.png"},
            {"Hot to Burn", "https://www.pragmaticplay.com/id/permainan/hot-to-burn-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/04/Hot-to-Burn%E2%84%A2_EN-_339x180-1.png"},
            {"Aztec Gems", "https://www.pragmaticplay.com/id/permainan/aztec-gems-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/02/thumbs-pt-site_Aztec-Gems_330x140px-1.png"},
            {"Joker’s Jewels", "https://www.pragmaticplay.com/id/permainan/jokers-jewels-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/03/thumbs_Jokers_jewels_330x140px.png"},
            {"Sweet Bonanza", "https://www.pragmaticplay.com/id/permainan/sweet-bonanza-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/03/Sweet-Bonanza%E2%84%A2_Thumb_339x180-3.png"},
            {"888 Dragons", "https://www.pragmaticplay.com/id/permainan/888-dragons-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/06/thumb_888-Dragons_330x140px-1.png"},
            {"Great Rhino", "https://www.pragmaticplay.com/id/permainan/great-rhino-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/04/new-thumbs-1.png"},
            {"Caishen’s Gold", "https://www.pragmaticplay.com/id/permainan/caishens-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/08/thumbs-pt-site_Cashien_s-Gold_330x140px.png"},
            {"5 Lions", "https://www.pragmaticplay.com/id/permainan/5-lions-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/05/thumbs_5_lions_330x140px.png"},
            {"Fire Strike", "https://www.pragmaticplay.com/id/permainan/fire-strike-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/09/Firestrike%E2%84%A2_339x180-1.png"},
            {"Sweet Bonanza Xmas", "https://www.pragmaticplay.com/id/permainan/sweet-bonanza-xmas-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/11/Sweet-Bonanza-Xmas%E2%84%A2_339x180.png"},
            {"Lucky Dragons", "https://www.pragmaticplay.com/id/permainan/lucky-dragons-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/07/Lucky-Dragons_330x140px-2.png"},
            {"Vegas Magic", "https://www.pragmaticplay.com/id/permainan/vegas-magic-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/09/thumb-Vegas-Magic_330x140px-2.png"},
            {"Diamond Strike", "https://www.pragmaticplay.com/id/permainan/diamond-strike-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/09/thumbs-pt-site_Diamond-Strike_330x140px-1.png"},
            {"8 Dragons", "https://www.pragmaticplay.com/id/permainan/8-dragons-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/05/thumb_8_Dragons_330x140px-1.png"},
            {"John Hunter and the Tomb of the Scarab Queen", "https://www.pragmaticplay.com/id/permainan/john-hunter-and-the-tomb-of-the-scarab-queen-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/08/John-Hunter-and-TOSQ%E2%84%A2_339x180_01-2.png"},
            {"Aztec Bonanza", "https://www.pragmaticplay.com/id/permainan/aztec-bonanza-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/02/Aztec-Bonanza%E2%84%A2_EN_03_339x180_01-1.png"},
            {"Fire 88", "https://www.pragmaticplay.com/id/permainan/fire-88-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/03/thumbs-pt-site_fire88_330x140px-1.png"},
            {"Mustang Gold", "https://www.pragmaticplay.com/id/permainan/mustang-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/12/Thumb_mustang-gold_339x180px-1.png"},
            {"Wild West Gold", "https://www.pragmaticplay.com/id/permainan/wild-west-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/03/Wild-West-Gold%E2%84%A2_EN_339x180_01-3.png"},
            {"Fruit Rainbow", "https://www.pragmaticplay.com/id/permainan/fruit-rainbow-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/03/Fruit-Rainbow%E2%84%A2_EN_339x180.png"},
            {"The Wild Machine", "https://www.pragmaticplay.com/id/permainan/the-wild-machine-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/02/The-Wild-Machine%E2%84%A2_EN_339x180_01-1.png"},
            {"Mysterious", "https://www.pragmaticplay.com/id/permainan/mysterious-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/02/Mysterious%E2%84%A2_EN_339x180.png"},
            {"Golden Beauty", "https://www.pragmaticplay.com/id/permainan/golden-beauty-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/02/Golden-Beauty%E2%84%A2_EN_339x180_01.png"},
            {"Master Joker", "https://www.pragmaticplay.com/id/permainan/master-joker-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/01/Master-Joker%E2%84%A2_EN_339x180_01.png"},
            {"Super 7s", "https://www.pragmaticplay.com/id/permainan/super-7s-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/01/Super7s%E2%84%A2_EN_339x180_03.png"},
            {"Release the Kraken", "https://www.pragmaticplay.com/id/permainan/release-the-kraken-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/01/ReleaseTheKraken%E2%84%A2_EN_339x180_01-1.png"},
            {"Buffalo King", "https://www.pragmaticplay.com/id/permainan/buffalo-king-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/11/Buffalo-King%E2%84%A2_EN_339x180_01.png"},
            {"Magic Journey", "https://www.pragmaticplay.com/id/permainan/magic-journey-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/12/Magic-Journey%E2%84%A2_EN_339x180_01-1.png"},
            {"Money Mouse", "https://www.pragmaticplay.com/id/permainan/money-mouse-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/01/Money-Mouse%E2%84%A2_EN_339x180_02-1.png"},
            {"Aladdin and the Sorcerer", "https://www.pragmaticplay.com/id/permainan/aladdin-and-the-sorcerer-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/10/Aladdin-and-the-Sorcerer%E2%84%A2_339x180-1.png"},
            {"Greek Gods", "https://www.pragmaticplay.com/id/permainan/greek-gods-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/11/Greek-Gods%E2%84%A2_EN_339x180_02-1.png"},
            {"Hercules and Pegasus", "https://www.pragmaticplay.com/id/permainan/hercules-and-pegasus-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/10/Hercules-Pegasus_339x180_01-2.png"},
            {"Tree of Riches", "https://www.pragmaticplay.com/id/permainan/tree-of-riches-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/08/Tree-of-Riches%E2%84%A2_339x180-1.png"},
            {"Honey Honey Honey", "https://www.pragmaticplay.com/id/permainan/honey-honey-honey-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/09/Honey-Honey-Honey%E2%84%A2_339x180-1.png"},
            {"Super Joker", "https://www.pragmaticplay.com/id/permainan/super-joker-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/08/Super-Joker_339x180-1.png"},
            {"Hot Chilli", "https://www.pragmaticplay.com/id/permainan/hot-chilli-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/06/Hot-Chilli%E2%84%A2_v02_339x180-3.png"},
            {"John Hunter and the Aztec Treasure", "https://www.pragmaticplay.com/id/permainan/john-hunter-and-the-aztec-treasure-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/06/JH-and-the-Aztec-treasure%E2%84%A2_339x180_02-2.png"},
            {"Monkey Warrior", "https://www.pragmaticplay.com/id/permainan/monkey-warrior-2-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/06/Monkey-warrior%E2%84%A2.png"},
            {"Caishen’s Cash", "https://www.pragmaticplay.com/id/permainan/caishens-cash-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/03/Caishens-Cah%E2%84%A2_339x180px-2.png"},
            {"5 Lions Gold", "https://www.pragmaticplay.com/id/permainan/5-lions-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/03/Thumb_5-Lions-Gold%E2%84%A2_339x180px-2.png"},
            {"The Great Chicken Escape", "https://www.pragmaticplay.com/id/permainan/the-great-chicken-escape-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/07/The-Great-Chicken-Escape%E2%84%A2_339x180px-1.png"},
            {"Vampires vs Wolves", "https://www.pragmaticplay.com/id/permainan/vampires-vs-wolves-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/07/VampireVsWolf%E2%84%A2_339x180-2-1.png"},
            {"Triple Jokers", "https://www.pragmaticplay.com/id/permainan/triple-jokers-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/03/Triple-Jokers%E2%84%A2_339x180px-1-1.png"},
            {"Wild Pixies", "https://www.pragmaticplay.com/id/permainan/wild-pixies-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/02/Thumb_Wild-Pixies_339x180px-2.png"},
            {"Pirate Gold", "https://www.pragmaticplay.com/id/permainan/pirate-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/03/Pirates-Code%E2%84%A2_Thumb_339x180_02-4.png"},
            {"The Dog House", "https://www.pragmaticplay.com/id/permainan/the-dog-house-megaways-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/07/DOHO_Megaways%E2%84%A2_EN_339x180.png"},
            {"Egyptian Fortunes", "https://www.pragmaticplay.com/id/permainan/egyptian-fortunes-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/02/Egyptian-Fortunes%E2%84%A2_Thumb_339x180-1-1.png"},
            {"Extra Juicy", "https://www.pragmaticplay.com/id/permainan/extra-juicy-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/01/thumb_Extra-Juicy%E2%84%A2_330x140px-1-1.png"},
            {"Wild Gladiators", "https://www.pragmaticplay.com/id/permainan/wild-gladiators-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/01/Wild-Gladiators%E2%84%A2_339x180px_03-2.png"},
            {"Golden Ox", "https://www.pragmaticplay.com/id/permainan/golden-ox/", "https://www.pragmaticplay.com/wp-content/uploads/2021/01/Golden-Ox_EN_339x180.png"},
            {"Treasure Horse", "https://www.pragmaticplay.com/id/permainan/treasure-horse-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/12/Treasure-Horse%E2%84%A2_339x180px-1.png"},
            {"Safari King", "https://www.pragmaticplay.com/id/permainan/safari-king-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2019/01/Safari-Kings%E2%84%A2_339x180px-2.png"},
            {"Leprechaun Carol", "https://www.pragmaticplay.com/id/permainan/leprechaun-carol-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/11/Leprechaun-Song%E2%84%A2_Thumb_339x180-1.png"},
            {"Triple Dragons", "https://www.pragmaticplay.com/id/permainan/triple-dragons-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/10/Thumb_Triple-Dragons_339x180px-2.png"},
            {"Ancient Egypt Classic", "https://www.pragmaticplay.com/id/permainan/ancient-egypt-classic-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/10/Thumb_Ancient-Egypt-Classic_339x180px-2-2.png"},
            {"Master Chen’s Fortune", "https://www.pragmaticplay.com/id/permainan/master-chens-fortune-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/09/thumb_Master-Chens-Fortune_339x180-1.png"},
            {"Da Vinci’s Treasure", "https://www.pragmaticplay.com/id/permainan/da-vincis-treasure-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/08/thumb_DaVincis-Treasure_339x180_ver2.png"},
            {"Peking Luck", "https://www.pragmaticplay.com/id/permainan/peking-luck-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/07/thumb_Peking_Luck_330x140-1-1.png"},
            {"Leprechaun Song", "https://www.pragmaticplay.com/id/permainan/leprechaun-song-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/08/thumb_Leprechaun_Song_339X180-1-1.png"},
            {"Asgard", "https://www.pragmaticplay.com/id/permainan/asgard-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/05/thumb_Asgard_330x140-1.png"},
            {"Madame Destiny Megaways", "https://www.pragmaticplay.com/id/permainan/madame-destiny-megaways/", "https://www.pragmaticplay.com/wp-content/uploads/2021/01/MDM_EN_339x180.png"},
            {"Jade Butterfly", "https://www.pragmaticplay.com/id/permainan/jade-butterfly-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/06/thumbs_jade_butterfly_330x140px-1-1.png"},
            {"Chilli Heat", "https://www.pragmaticplay.com/id/permainan/chilli-heat-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/01/thumbs-pt-site_Chilli-Heat_330x140px-1.png"},
            {"Fairytale Fortune", "https://www.pragmaticplay.com/id/permainan/fairytale-fortune-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/03/thumb-Fairytale-Fortune_330x140px-1.png"},
            {"Ancient Egypt", "https://www.pragmaticplay.com/id/permainan/ancient-egypt-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/01/thumb-Ancient-Egypt_330x140-2px-1.png"},
            {"Lucky New Year", "https://www.pragmaticplay.com/id/permainan/lucky-new-year-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2018/01/thumb-Lucky-New-Year_330x140px-2-1.png"},
            {"Monkey Madness", "https://www.pragmaticplay.com/id/permainan/monkey-madness-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/11/thumbs-pt-site_Monkey-Madness_330x140px-1.png"},
            {"Gold Rush", "https://www.pragmaticplay.com/id/permainan/gold-rush-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/12/thumbs-pt-site_Gold-Rush_330x140px-2.png"},
            {"Santa", "https://www.pragmaticplay.com/id/permainan/santa-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/11/thumbs-pt-site_Santa_330x140px-3.png"},
            {"Panda’s Fortune", "https://www.pragmaticplay.com/id/permainan/pandas-fortune-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/11/thumbs-pt-site_Panda-Fortune_330x140px-1.png"},
            {"7 Piggies", "https://www.pragmaticplay.com/id/permainan/7-piggies-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/10/thumbs-pt-site_7_Piggies_330x140px-1.png"},
            {"Diamonds are Forever", "https://www.pragmaticplay.com/id/permainan/diamonds-are-forever-3-lines-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/thumbs-pt-site_330x140px.png"},
            {"888 Gold", "https://www.pragmaticplay.com/id/permainan/888-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/02/thumbs-pt-site_888_GOLD_330x140px-2.png"},
            {"Irish Charms", "https://www.pragmaticplay.com/id/permainan/irish-charms-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/03/thumbs-pt-site_IRISH-CHARMS__330x140px-1-1.png"},
            {"Triple Tigers", "https://www.pragmaticplay.com/id/permainan/triple-tigers-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/11/thumb-TRIPLE-TIGERS_330x140px-1.png"},
            {"Tales of Egypt", "https://www.pragmaticplay.com/id/permainan/tales-of-egypt-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/59_Tales-of-Egypt_desktop-330x140px-1.png"},
            {"Sugar Rush", "https://www.pragmaticplay.com/id/permainan/sugar-rush-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/53_Sugar-Rush_desktop-330x140px-1.png"},
            {"Lady of the Moon", "https://www.pragmaticplay.com/id/permainan/lady-of-the-moon-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/35_Lady-of-the-Moon_desktop_330x140px-2.png"},
            {"Great Reef", "https://www.pragmaticplay.com/id/permainan/great-reef-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/33_Great-Reef_desktop-330x140px-1.png"},
            {"Glorious Rome", "https://www.pragmaticplay.com/id/permainan/glorious-rome-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/30_Glorious-Rome_desktop-330x140px-1.png"},
            {"Aladdin’s Treasure", "https://www.pragmaticplay.com/id/permainan/aladdins-treasure-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/12_Aladdins-Treasure_desktop-330x140px-1.png"},
            {"Hockey League", "https://www.pragmaticplay.com/id/permainan/hockey-league-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/thumbs_Hockey_remake_330x140px-1.png"},
            {"Magic Crystals", "https://www.pragmaticplay.com/id/permainan/magic-crystals-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/thumb-_Magic-Crystals__330x140px.png"},
            {"The Catfather", "https://www.pragmaticplay.com/id/permainan/the-catfather-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/thumb_The-Catfather-__330x140px.png"},
            {"Lady Godiva", "https://www.pragmaticplay.com/id/permainan/lady-godiva-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/06_Lady-Godiva_desktop_330x140px-1.png"},
            {"Mighty Kong", "https://www.pragmaticplay.com/id/permainan/mighty-kong-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/05_Mighty-Kong_desktop-330x140px-5.png"},
            {"Hockey League", "https://www.pragmaticplay.com/id/permainan/hockey-league-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/thumbs_Hockey_remake_330x140px-1.png"},
            {"Hot Safari", "https://www.pragmaticplay.com/id/permainan/hot-safari-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/03_Hot-Safari_desktop_330x140px-2.png"},
            {"Romeo and Juliet", "https://www.pragmaticplay.com/id/permainan/romeo-and-juliet-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/02_Romeo-and-Juliet_desktop_330x140px-2.png"},
            {"Dwarven Gold Deluxe", "https://www.pragmaticplay.com/id/permainan/dwarven-gold-deluxe-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/thumbs-pt-site_Dwarven-Gold-Deluxe_330x140px-1.png"},
            {"Lucky Dragons", "https://www.pragmaticplay.com/id/permainan/lucky-dragons-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/07/Lucky-Dragons_330x140px-2.png"},
            {"Beowulf", "https://www.pragmaticplay.com/id/permainan/beowulf-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/09/thumbs-pt-site_BEOWULF_330x140px-1.png"},
            {"The Catfather Part II", "https://www.pragmaticplay.com/id/permainan/the-catfather-part-ii-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/11/thumbs-pt-site_Catz-Part-II_330x140px-2.png"},
            {"Hercules Son of Zeus", "https://www.pragmaticplay.com/id/permainan/hercules-son-of-zeus-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/12/thumbs-pt-site_Hercules-son-of-Zeus_330x140px-2.png"},
            {"Queen of Atlantis", "https://www.pragmaticplay.com/id/permainan/queen-of-atlantis-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/03/thumbs-pt-site_QUEEN-of-Atlantis__330x140px-4-1.png"},
            {"Wolf Gold", "https://www.pragmaticplay.com/id/permainan/wolf-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/04/thumb__WOLF_GOLD__330x140px.png"},
            {"Jurassic Giants", "https://www.pragmaticplay.com/id/permainan/jurassic-giants-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/06/thumbs_Jurassic-Giants_330x140px-1.png"},
            {"Pixie Wings", "https://www.pragmaticplay.com/id/permainan/pixie-wings-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/07/thumbs-pt-sitePixie_Wings_330x140px-2-1.png"},
            {"Dwarven Gold", "https://www.pragmaticplay.com/id/permainan/dwarven-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/25_Dwarven-Gold_desktop_330x140px-1.png"},
            {"3 Genie Wishes", "https://www.pragmaticplay.com/id/permainan/3-genie-wishes-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/11/thumbs-pt-site_3-GENIE-WISHES_330x140px.png"},
            {"Vegas Nights", "https://www.pragmaticplay.com/id/permainan/vegas-nights-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/09/thumbs-pt-site_Vegas-Nights_330x140px-3.png"},
            {"Gold Train", "https://www.pragmaticplay.com/id/permainan/gold-train-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/05/thumbs-pt-site_Gold-Train_330x140px-1-2.png"},
            {"Panther Queen", "https://www.pragmaticplay.com/id/permainan/panther-queen-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/03/thumbs-pt-site__Panther-Queen__330x140px-1.png"},
            {"3 Kingdoms – Battle of Red Cliffs", "https://www.pragmaticplay.com/id/permainan/3-kingdoms-battle-of-red-cliffs-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/04/thumb-_3-Kingdoms__330x140px.png"},
            {"Journey to the West", "https://www.pragmaticplay.com/id/permainan/journey-to-the-west-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/10/thumbs-pt-site_Journey-to-the-West_330x140px.png"},
            {"Wild Spells", "https://www.pragmaticplay.com/id/permainan/wild-spells-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/08/thumbs-pt-site_Wild_Spells_330x140px-2.png"},
            {"Queen of Gold", "https://www.pragmaticplay.com/id/permainan/queen-of-gold-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2017/02/thumbs-pt-site_QUEEN-OF-GOLD_330x140px-2.png"},
            {"7 Monkeys", "https://www.pragmaticplay.com/id/permainan/7-monkeys-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/05/11_7-Monkeys_desktop_330x140px-1.png"},
            {"Dragon Kingdom", "https://www.pragmaticplay.com/id/permainan/dragon-kingdom-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2016/12/thumbs-pt-site_3-Dragon-Kingdom_330x140px-1.png"},
            {"Wild Wild Riches", "https://www.pragmaticplay.com/id/permainan/wild-wild-riches-slot/", "https://www.pragmaticplay.com/wp-content/uploads/2020/09/Wild_Wild_Riches%E2%84%A2_EN_339x180.png"},
    };

    public static ArrayList<Game> getListData(){
        ArrayList<Game> list = new ArrayList<>();
        for (String[] aData : data) {
            Game game = new Game();
            game.setJudul(aData[0]);
            game.setLink(aData[1]);
            game.setPhoto(aData[2]);
            list.add(game);
        }
        return list;
    }
}
